[STORAGE]
SQLITE_DB = "data/db/mcp_server.db"
SCREENSHOTS_DIR = "data/screenshots"
PDFS_DIR = "data/pdfs"
PROJECTS_DIR = "data/projects"
LOGS_DIR = "data/logs"
REPOS_DIR = "data/repos"

[API_ENDPOINTS]
BING = "https://api.bing.microsoft.com/v7.0/search"
GOOGLE = "https://www.googleapis.com/customsearch/v1"
OLLAMA = "http://127.0.0.1:11434"
OPENAI = "https://api.openai.com"
LM_STUDIO = "http://localhost:1234/v1"

[LOGGING]
LOG_REST_API = "false"
LOG_PROMPTS = "false"

[TIMEOUT]
INFERENCE = 300

[AWS]
PROFILE = "chatbot"

[CHROMA]
PATH = "data/chroma"
EMBEDDING_MODEL = "all-MiniLM-L6-v2"

[MODEL]
TINY = "Gemini 1.5 Flash-8B"
LITE = "Gemini 2.0 Flash Lite"
BASE = "Gemini 2.0 Flash"
THINK = "Gemini 2.5 Flash"
VISION = "Gemini 2.0 Flash"
IMAGE_GEN = "Gemini 2.0 Flash Img Gen"
AUDIO_GEN = "Gemini 2.0 Flash"
VIDEO_GEN = "Gemini 2.0 Flash"
PRO = "Gemini 2.5 Pro"
LIVE = "Gemini 2.0 Flash Live"

[GOOGLE]
USE_VERTEXAI = 0
CLOUD_PROJECT = ""
CLOUD_LOCATION = ""
